{"now": "2020/10/29 20:47:07 +0100", "version": "13.0.7", "plugin": "vscode/1.50.1 vscode-wakatime/4.0.9", "time": 1604000744.058214, "level": "WARNING", "message": "Traceback (most recent call last):\n  File \"urllib3/connectionpool.py\", line 376, in _make_request\n  File \"urllib3/connectionpool.py\", line 994, in _validate_conn\n  File \"urllib3/connection.py\", line 352, in connect\n  File \"urllib3/util/ssl_.py\", line 370, in ssl_wrap_socket\n  File \"ssl.py\", line 500, in wrap_socket\n  File \"ssl.py\", line 1040, in _create\n  File \"ssl.py\", line 1309, in do_handshake\nsocket.timeout: _ssl.c:1091: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"requests/adapters.py\", line 439, in send\n  File \"urllib3/connectionpool.py\", line 719, in urlopen\n  File \"urllib3/util/retry.py\", line 400, in increment\n  File \"urllib3/packages/six.py\", line 735, in reraise\n  File \"urllib3/connectionpool.py\", line 665, in urlopen\n  File \"urllib3/connectionpool.py\", line 379, in _make_request\n  File \"urllib3/connectionpool.py\", line 330, in _raise_timeout\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wakatime.com', port=443): Read timed out. (read timeout=60)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"wakatime/api.py\", line 98, in send_heartbeats\n  File \"requests/sessions.py\", line 578, in post\n  File \"requests/sessions.py\", line 530, in request\n  File \"requests/sessions.py\", line 643, in send\n  File \"requests/adapters.py\", line 529, in send\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wakatime.com', port=443): Read timed out. (read timeout=60)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"wakatime/offlinequeue.py\", line 57, in push\nsqlite3.OperationalError: database is locked\n"}
{"now": "2020/10/29 20:47:07 +0100", "version": "13.0.7", "plugin": "vscode/1.50.1 vscode-wakatime/4.0.9", "time": 1604000744.704471, "level": "WARNING", "message": "Traceback (most recent call last):\n  File \"urllib3/connectionpool.py\", line 376, in _make_request\n  File \"urllib3/connectionpool.py\", line 994, in _validate_conn\n  File \"urllib3/connection.py\", line 352, in connect\n  File \"urllib3/util/ssl_.py\", line 370, in ssl_wrap_socket\n  File \"ssl.py\", line 500, in wrap_socket\n  File \"ssl.py\", line 1040, in _create\n  File \"ssl.py\", line 1309, in do_handshake\nsocket.timeout: _ssl.c:1091: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"requests/adapters.py\", line 439, in send\n  File \"urllib3/connectionpool.py\", line 719, in urlopen\n  File \"urllib3/util/retry.py\", line 400, in increment\n  File \"urllib3/packages/six.py\", line 735, in reraise\n  File \"urllib3/connectionpool.py\", line 665, in urlopen\n  File \"urllib3/connectionpool.py\", line 379, in _make_request\n  File \"urllib3/connectionpool.py\", line 330, in _raise_timeout\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wakatime.com', port=443): Read timed out. (read timeout=60)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"wakatime/api.py\", line 98, in send_heartbeats\n  File \"requests/sessions.py\", line 578, in post\n  File \"requests/sessions.py\", line 530, in request\n  File \"requests/sessions.py\", line 643, in send\n  File \"requests/adapters.py\", line 529, in send\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wakatime.com', port=443): Read timed out. (read timeout=60)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"wakatime/offlinequeue.py\", line 57, in push\nsqlite3.OperationalError: database is locked\n"}
